// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings worker-configuration.d.ts`

interface CloudflareBindings {
	AGENT_CONNECTION: DurableObjectNamespace<import("./src/index").AgentConnection>;
	CLIENT_CONNECTION: DurableObjectNamespace<import("./src/index").ClientConnection>;
	MESSAGE_ROUTER: DurableObjectNamespace<import("./src/index").MessageRouter>;
	DB: D1Database;
}
