// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings src/types.d.ts`

interface CloudflareBindings {
	AGENT_CONNECTION: DurableObjectNamespace<import("./index").AgentConnection>;
	CLIENT_CONNECTION: DurableObjectNamespace<import("./index").ClientConnection>;
	MESSAGE_ROUTER: DurableObjectNamespace<import("./index").MessageRouter>;
	DB: D1Database;
}
